/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    ButtonGroup: typeof import('primevue/buttongroup')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataView: typeof import('primevue/dataview')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dock: typeof import('primevue/dock')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Password: typeof import('primevue/password')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    Rating: typeof import('primevue/rating')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Slider: typeof import('primevue/slider')['default']
    Steps: typeof import('primevue/steps')['default']
    TabMenu: typeof import('primevue/tabmenu')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TreeTable: typeof import('primevue/treetable')['default']
  }
}

// For TSX support
declare global {
  const AutoComplete: typeof import('primevue/autocomplete')['default']
  const Avatar: typeof import('primevue/avatar')['default']
  const Breadcrumb: typeof import('primevue/breadcrumb')['default']
  const Button: typeof import('primevue/button')['default']
  const ButtonGroup: typeof import('primevue/buttongroup')['default']
  const Card: typeof import('primevue/card')['default']
  const Checkbox: typeof import('primevue/checkbox')['default']
  const Column: typeof import('primevue/column')['default']
  const DataTable: typeof import('primevue/datatable')['default']
  const DataView: typeof import('primevue/dataview')['default']
  const DatePicker: typeof import('primevue/datepicker')['default']
  const Dialog: typeof import('primevue/dialog')['default']
  const Dock: typeof import('primevue/dock')['default']
  const Dropdown: typeof import('primevue/dropdown')['default']
  const FileUpload: typeof import('primevue/fileupload')['default']
  const IconField: typeof import('primevue/iconfield')['default']
  const InputIcon: typeof import('primevue/inputicon')['default']
  const InputNumber: typeof import('primevue/inputnumber')['default']
  const InputSwitch: typeof import('primevue/inputswitch')['default']
  const InputText: typeof import('primevue/inputtext')['default']
  const Menu: typeof import('primevue/menu')['default']
  const Message: typeof import('primevue/message')['default']
  const MultiSelect: typeof import('primevue/multiselect')['default']
  const Password: typeof import('primevue/password')['default']
  const ProgressBar: typeof import('primevue/progressbar')['default']
  const ProgressSpinner: typeof import('primevue/progressspinner')['default']
  const RadioButton: typeof import('primevue/radiobutton')['default']
  const Rating: typeof import('primevue/rating')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Select: typeof import('primevue/select')['default']
  const Skeleton: typeof import('primevue/skeleton')['default']
  const Slider: typeof import('primevue/slider')['default']
  const Steps: typeof import('primevue/steps')['default']
  const TabMenu: typeof import('primevue/tabmenu')['default']
  const TabPanel: typeof import('primevue/tabpanel')['default']
  const TabView: typeof import('primevue/tabview')['default']
  const Tag: typeof import('primevue/tag')['default']
  const Textarea: typeof import('primevue/textarea')['default']
  const TreeTable: typeof import('primevue/treetable')['default']
}